live_config_reload = true

[font]
size = 15

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 1
y = 15

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceAr Nerd Font Mono"
style = "Light"

[font.offset]
x = 2
y = 30

[window]
decorations = "buttonless"
dynamic_padding = false
#opacity = 0.93

[window.padding]
x = 10
y = 18
